// SPDX-License-Identifier: AGPL-3.0-or-later
// Writes the Figma specs (specs/*.figma.json) from the live design pages.
//
//   npm install                      once, in figma/components/
//   node extract.mjs                 rewrite every spec
//   node extract.mjs --check         exit 1 if any spec differs from the pages
//   node extract.mjs button badge    only these pages
//   --base http://localhost:8144     the running app (default 8144); the
//                                    pages are static, nothing is written
//
// Each page is loaded in Chrome in the dark theme, walk.js turns its
// specimens into layout trees, and the native checkboxes are sampled from a
// screenshot (the browser draws them; no style says their colours). The
// specs are therefore generated, never edited: change the CSS or the page,
// then run this again. --check is the drift test.

import { chromium } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, 'specs');

// In build order: a set must come after any set it holds instances of.
export const PAGES = [
  ['button', 'Button'],
  ['input', 'Input'],
  ['textarea', 'Textarea'],
  ['select', 'Select'],
  ['checkbox', 'Checkbox'],
  ['toggle', 'Toggle'],
  ['badge', 'Badge'],
  ['button-group', 'Button group'],
  ['tooltip', 'Tooltip'],
  ['action-menu', 'Action menu'],
  ['disclosure', 'Disclosure'],
  ['search-bar', 'Search bar'],
  ['chat-bar', 'Chat bar'],
];

const args = process.argv.slice(2);
const check = args.includes('--check');
const bi = args.indexOf('--base');
const base = bi >= 0 ? args[bi + 1] : 'http://localhost:8144';
const only = args.filter((a, i) => !a.startsWith('--') && args[i - 1] !== '--base');

const browser = await chromium.launch({ channel: 'chrome' }).catch(() => chromium.launch());
const page = await browser.newPage({ viewport: { width: 1400, height: 1000 }, deviceScaleFactor: 1 });
await page.addInitScript(() => { try { localStorage.setItem('rag_theme', 'dark'); } catch (e) {} });
const walkSrc = fs.readFileSync(path.join(HERE, 'walk.js'), 'utf8');

// Sample a native checkbox: its well, its rule and (checked) its mark.
async function sampleCheckbox(n) {
  const el = page.locator(`[data-figma-cb="${n.cb}"]`);
  const shot = (await el.screenshot({ scale: 'device', animations: 'disabled' })).toString('base64');
  return page.evaluate(async ([src, checked]) => {
    const img = await new Promise(r => { const i = new Image(); i.onload = () => r(i); i.src = 'data:image/png;base64,' + src; });
    const c = document.createElement('canvas'); c.width = img.width; c.height = img.height;
    const x = c.getContext('2d'); x.drawImage(img, 0, 0);
    const at = (a, b) => { const d = x.getImageData(a, b, 1, 1).data; return [d[0], d[1], d[2]]; };
    const css = v => `rgb(${v[0]}, ${v[1]}, ${v[2]})`;
    const W = img.width, H = img.height, mid = Math.floor(H / 2);
    const rule = at(0, mid);
    const well = at(Math.max(2, Math.round(W * 0.12)), Math.round(H * 0.12));
    const out = { fill: window.__mcPaint(css(well)), rule: window.__mcPaint(css(rule)) };
    if (checked) {
      // the mark: the pixel furthest from the fill, inside the rounded
      // corners (where the page shows through)
      let best = null, far = 0;
      const i0 = Math.round(W * 0.2), i1 = Math.round(W * 0.8);
      const all = x.getImageData(i0, i0, i1 - i0, i1 - i0).data;
      for (let i = 0; i < all.length; i += 4) {
        const dd = Math.abs(all[i] - well[0]) + Math.abs(all[i + 1] - well[1]) + Math.abs(all[i + 2] - well[2]);
        if (dd > far) { far = dd; best = [all[i], all[i + 1], all[i + 2]]; }
      }
      out.mark = window.__mcPaint(css(best));
      if (out.rule && out.fill && out.rule.hex === out.fill.hex) out.rule = null;
    }
    return out;
  }, [shot, n.checked]);
}

function* nodes(n) {
  yield n;
  if (n.type === 'instance') yield* nodes(n.tree);
  for (const c of n.children || []) yield* nodes(c);
}

let failed = false;
for (const [slug, title] of PAGES) {
  if (only.length && !only.includes(slug)) continue;
  await page.goto(`${base}/static/design/${slug}.html`, { waitUntil: 'networkidle' });
  await page.evaluate(() => document.fonts.ready);
  await page.waitForTimeout(150);
  await page.addScriptTag({ content: walkSrc });
  const res = await page.evaluate(() => window.__mcWalk());
  for (const s of res.sets) for (const v of s.variants)
    for (const n of nodes(v.tree)) if (n.type === 'checkbox') Object.assign(n, await sampleCheckbox(n));
  for (const s of res.sets) for (const v of s.variants)
    for (const n of nodes(v.tree)) if (n.type === 'checkbox') delete n.cb;
  for (const w of res.warnings) console.warn(`${slug}: ${w}`);

  const spec = {
    $comment: `Generated by figma/components/extract.mjs from static/design/${slug}.html. Do not edit: change the CSS or the page and run the extractor again. Lengths are px at ${res.remPx}px per rem; {px, token} binds to the variable of that token, a bare number is a literal. Colours are {hex, token?, opacity?}; hex is the dark value, used when the file has no variable by that name.`,
    name: title,
    order: PAGES.findIndex(p => p[0] === slug),
    page: `static/design/${slug}.html`,
    remPx: res.remPx,
    fonts: { ui: 'CMU Sans Serif Demi Condensed', serif: 'Old Standard TT', mono: 'Roboto Mono' },
    fallback: res.fallback,
    sets: res.sets,
  };
  const file = path.join(OUT, `${slug}.figma.json`);
  const text = JSON.stringify(spec, null, 1) + '\n';
  if (check) {
    // git may check the file out with CRLF (core.autocrlf); compare the text
    const old = fs.existsSync(file) ? fs.readFileSync(file, 'utf8').replace(/
/g, '
') : '';
    if (old !== text) { console.log(`${slug}: differs from ${path.relative(process.cwd(), file)}`); failed = true; }
    else console.log(`${slug}: ok`);
  } else {
    fs.mkdirSync(OUT, { recursive: true });
    fs.writeFileSync(file, text);
    const counts = res.sets.map(s => `${s.name} ${s.variants.length}`).join(', ');
    console.log(`${slug}: ${counts}`);
  }
}
await browser.close();
if (failed) { console.log('Specs are out of date: run `node extract.mjs` and commit the result.'); process.exit(1); }
