// SPDX-License-Identifier: AGPL-3.0-or-later
// Bundles the icons for the Figma Icons plugin: writes icons.figma.json with
// every SVG in static/icons/ that a card draws, keyed by what it stands
// for (a card type, a category, a dream tone, a thing category), from the
// mapping in static/js/card.js. The plugin can't read the disk, so it takes
// the SVGs from this file.
//
//   node figma/icons/icons.mjs           write icons.figma.json
//   node figma/icons/icons.mjs --check   exit 1 if it is stale

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(HERE, '..', '..');
const ICONS = path.join(ROOT, 'static', 'icons');
const OUT = path.join(HERE, 'icons.figma.json');

const { TYPE_ICONS, SUBTYPE_ICONS, ONE_VERSION } =
  await import(pathToFileURL(path.join(ROOT, 'static', 'js', 'card.js')).href);

// One row per thing an icon stands for, in the icons page's order: the
// card types, then each type's subtypes.
const uses = [];
for (const [type, icon] of Object.entries(TYPE_ICONS)) uses.push({ for: type, group: 'card type', icon });
const GROUP = { category: 'category', dream: 'dream tone', thing: 'thing category' };
for (const [type, subs] of Object.entries(SUBTYPE_ICONS))
  for (const [sub, icon] of Object.entries(subs)) uses.push({ for: sub, group: GROUP[type] ?? type, icon });

const keys = uses.map(u => u.for);
const dupes = keys.filter((k, i) => keys.indexOf(k) !== i);
if (dupes.length) throw new Error(`a key stands for two things: ${dupes.join(', ')}`);

const svgs = {};
for (const icon of new Set(uses.map(u => u.icon))) {
  const read = f => fs.readFileSync(path.join(ICONS, f + '.svg'), 'utf8').trim();
  const outline = read(icon);
  svgs[icon] = { filled: ONE_VERSION.has(icon) ? outline : read(icon + '-filled'), outline };
}

const text = JSON.stringify({
  $comment: 'GENERATED by figma/icons/icons.mjs from static/js/card.js and static/icons/; do not edit. Read by figma/icons/code.js, which builds the Icon set from it.',
  name: 'Icon',
  size: 24,
  // the paint, by token name; the fallback is --text-accent's dark value
  color: { token: 'text-accent', fallback: '#d99e5b' },
  uses,
  svgs,
}, null, 1) + '\n';

if (process.argv.includes('--check')) {
  const now = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (now !== text) { console.log('icons.figma.json is stale: run node figma/icons/icons.mjs'); process.exit(1); }
  console.log(`icons.figma.json is current (${uses.length} uses, ${Object.keys(svgs).length} icons)`);
} else {
  fs.writeFileSync(OUT, text);
  console.log(`wrote icons.figma.json: ${uses.length} uses, ${Object.keys(svgs).length} icons`);
}
